"""
Shared protocol definitions for the LAN communication system.
Defines message types and constants used across server and client.
"""

# TCP Message Types
MSG_REGISTER = "REGISTER"
MSG_UDP_REGISTER = "UDP_REGISTER"
MSG_CHAT = "CHAT"
MSG_FILE_META = "FILE_META"
MSG_FILE_REQUEST = "FILE_REQUEST"
MSG_FILE_DATA = "FILE_DATA"
MSG_SCREEN_START = "SCREEN_START"
MSG_SCREEN_STOP = "SCREEN_STOP"
MSG_SCREEN_FRAME = "SCREEN_FRAME"
MSG_USER_LIST = "USER_LIST"
MSG_DISCONNECT = "DISCONNECT"

# UDP Message Types
MSG_VIDEO = "VIDEO"
MSG_AUDIO = "AUDIO"

# Server Ports
TCP_PORT = 5555
UDP_VIDEO_PORT = 5556
UDP_AUDIO_PORT = 5557

# Configuration
MAX_PACKET_SIZE = 65507
VIDEO_QUALITY = 50
AUDIO_CHUNK = 1024
AUDIO_RATE = 44100
AUDIO_CHANNELS = 1
VIDEO_WIDTH = 640
VIDEO_HEIGHT = 480
VIDEO_FPS = 15

